# Generated by Django 5.2 on 2026-01-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_bio_remove_profile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verification_token_created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
